# Generated by Django 5.2.7 on 2025-11-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_description_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'english'), ('de', 'deutsch'), ('ru', 'russian')], default='de', max_length=2),
        ),
    ]
